name: kito
description: A powerful, fine-grained reactive animation library for Flutter inspired by anime.js
version: 0.1.0
repository: https://github.com/darmie/kito

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0

  # Reactive primitives
  kito_reactive: ^0.1.0

  # State machine library
  kito_fsm: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
